version: '3.8'
networks:
  dev:
services:
  database:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      dev:

  server:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    tty: true
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      dev:

  client:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      dev:

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - server
      - client
    ports:
      - 8080:80
    networks:
      dev:

volumes:
  pgdata:
